FROM ubuntu:24.04 AS build

ARG FEATURES

RUN apt-get clean && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    apt-get install -y curl build-essential
RUN apt-get install iproute2 -y
RUN apt-get install net-tools
RUN apt-get install -y rustup
RUN rustup default stable
RUN sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.7/install)" && \
    /root/.local/share/solana/install/active_release/bin/sdk/sbf/scripts/install.sh

ENV PATH=${PATH}:/root/.local/share/solana/install/active_release/bin

COPY hello_world /opt/hello_world

WORKDIR /opt/hello_world/

RUN cargo build-sbf

#FROM anzaxyz/agave:v2.1.7
#COPY --from=build /opt/hello_world/target/deploy/hello_world.so /opt/
#COPY --from=build /opt/hello_world/ci /opt/ci
#RUN chmod +x /opt/ci/start_solana.sh

RUN echo "solana"


#FROM ubuntu:24.04 AS build
#
#ARG FEATURES
#
#RUN apt-get clean && \
#    apt-get update && \
#    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
#    apt-get install -y curl build-essential
#
#RUN apt-get install -y rustup
#RUN rustup default stable
#RUN sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.7/install)" && \
#    /root/.local/share/solana/install/active_release/bin/sdk/sbf/scripts/install.sh
#
#ENV PATH=${PATH}:/root/.local/share/solana/install/active_release/bin
#
#COPY hello_world /opt/hello_world
#
#WORKDIR /opt/hello_world/
#
#RUN cargo build-sbf
#
#FROM anzaxyz/agave:v2.1.7
#COPY --from=build /opt/hello_world/target/deploy/hello_world.so /opt/
#COPY --from=build /opt/hello_world/ci /opt/ci
#RUN chmod +x /opt/ci/start_solana.sh
#
#ENTRYPOINT [ "/opt/ci/start_solana.sh" ]



